name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      # Runs a single command using the runners shell
      - name: Compile
        run: mvn compile
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: '${{github.job}}-${{github.run_number}}'
          path: 'target/*'
          retention-days: 7

  test:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Test
        run: mvn test
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: '${{github.job}}-${{github.run_number}}'
          path: |
            target/surefire-reports/*
            target/site/jacoco/*
          retention-days: 7

  package:
    runs-on: self-hosted
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Package
        run: mvn package
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: '${{github.job}}-${{github.run_number}}'
          path: 'target/*.war'
          retention-days: 7

  deploy_test:
    runs-on: self-hosted
    needs: package
    environment: 'deploy_test'
    steps:
      - uses: actions/checkout@v3
      - name: Deploy
        run: |
          echo -e 'FROM tomcat:8.5.78-jdk17-openjdk-slim-bullseye \n COPY ./target/game2048.war /usr/local/tomcat/webapps' | docker build -t game2048 -f- .
          docker run --rm -d --name tomcat -p 8080:8080 game2048

  stop_test:
    runs-on: self-hosted
    needs: deploy_test
    environment: 'deploy_test'
    steps:
      - uses: actions/checkout@v3
      - uses: docker-practice/actions-setup-docker@master
      - name: Stop
        run: |
          docker rm --force tomcat
          docker image rm --force game2048
          docker rm --force tomcat
          docker image rm --force game2048